version: "3.8"
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

  db:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  data: {}
